In [8]:
import torch
import numpy as np

np.set_printoptions(precision=3)
torch.cuda.is_available()

True

In [9]:
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b) 

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [10]:
t_ones = torch.ones(2, 3)
t_ones.shape

torch.Size([2, 3])

In [11]:
print(t_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [13]:
rand_tensor = torch.rand(2,3)
print(rand_tensor)

tensor([[0.8195, 0.0542, 0.7816],
        [0.2035, 0.8452, 0.0606]])
