In [2]:
import torch
import numpy as np

np.set_printoptions(precision=3)

In [3]:
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)
t_a = torch.tensor(a)
t_b = torch.from_numpy(b)
print(t_a)
print(t_b) 

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [4]:
t_ones = torch.ones(2, 3)
t_ones.shape

torch.Size([2, 3])

In [5]:
print(t_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
