In [1]:
import torch

In [2]:
!nvidia-smi

Mon Apr 29 21:29:46 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.76.01              Driver Version: 552.22         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090 Ti     On  |   00000000:03:00.0  On |                  Off |
|  0%   53C    P8             24W /  480W |    1703MiB /  24564MiB |     29%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors
### Creating tensors

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [10]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [14]:
# matrix
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
matrix.ndim

2

In [16]:
matrix.shape

torch.Size([2, 2])

In [17]:
matrix[1]

tensor([ 9, 10])

In [18]:
# tensor
tensor = torch.tensor([[[1, 2, 3], [2, 3, 4], [12, 2, 4]]])

tensor

tensor([[[ 1,  2,  3],
         [ 2,  3,  4],
         [12,  2,  4]]])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

In [21]:
tensor[0]

tensor([[ 1,  2,  3],
        [ 2,  3,  4],
        [12,  2,  4]])