In [1]:
import torch

In [2]:
!nvidia-smi

Mon Apr 29 21:29:46 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.76.01              Driver Version: 552.22         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090 Ti     On  |   00000000:03:00.0  On |                  Off |
|  0%   53C    P8             24W /  480W |    1703MiB /  24564MiB |     29%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors
### Creating tensors

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [10]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [14]:
# matrix
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [15]:
matrix.ndim

2

In [16]:
matrix.shape

torch.Size([2, 2])

In [17]:
matrix[1]

tensor([ 9, 10])

In [18]:
# tensor
tensor = torch.tensor([[[1, 2, 3], [2, 3, 4], [12, 2, 4]]])

tensor

tensor([[[ 1,  2,  3],
         [ 2,  3,  4],
         [12,  2,  4]]])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

In [21]:
tensor[0]

tensor([[ 1,  2,  3],
        [ 2,  3,  4],
        [12,  2,  4]])

### Random tensors


In [22]:
tensor = torch.rand(3, 4)
tensor

tensor([[0.5931, 0.1823, 0.6019, 0.6811],
        [0.5761, 0.3635, 0.9510, 0.8685],
        [0.7386, 0.1770, 0.8673, 0.8961]])

In [24]:
tensor.shape

torch.Size([3, 4])

In [25]:
tensor.ndim

2

In [26]:
image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel
image_tensor

tensor([[[0.5556, 0.5070, 0.2121],
         [0.9702, 0.8898, 0.0544],
         [0.9739, 0.7541, 0.0870],
         ...,
         [0.8616, 0.2872, 0.4514],
         [0.6444, 0.2466, 0.4214],
         [0.5869, 0.0563, 0.0773]],

        [[0.4889, 0.9028, 0.0468],
         [0.4633, 0.1114, 0.3259],
         [0.7094, 0.2708, 0.8096],
         ...,
         [0.9449, 0.3702, 0.3189],
         [0.5450, 0.6762, 0.4300],
         [0.2505, 0.9011, 0.3179]],

        [[0.3255, 0.7719, 0.1144],
         [0.6837, 0.1215, 0.3098],
         [0.2806, 0.9772, 0.1212],
         ...,
         [0.1838, 0.0961, 0.7554],
         [0.3364, 0.4847, 0.7112],
         [0.6264, 0.3816, 0.6882]],

        ...,

        [[0.3314, 0.2018, 0.5692],
         [0.4381, 0.6692, 0.3517],
         [0.1909, 0.2642, 0.5034],
         ...,
         [0.0994, 0.3579, 0.5478],
         [0.5421, 0.9193, 0.9405],
         [0.5565, 0.6851, 0.5563]],

        [[0.3079, 0.6785, 0.0507],
         [0.0398, 0.4130, 0.8126],
         [0.

In [27]:
image_tensor.ndim

3