In [1]:
import torch

In [2]:
!nvidia-smi

Sat Aug 17 16:15:36 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.31.01              Driver Version: 560.81         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090 Ti     On  |   00000000:03:00.0  On |                  Off |
|  0%   49C    P8             22W /  480W |    1920MiB /  24564MiB |      9%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors
### Creating tensors

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# matrix
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
matrix[1]

tensor([ 9, 10])

In [15]:
# tensor
tensor = torch.tensor([[[1, 2, 3], [2, 3, 4], [12, 2, 4]]])

tensor

tensor([[[ 1,  2,  3],
         [ 2,  3,  4],
         [12,  2,  4]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape

torch.Size([1, 3, 3])

In [18]:
tensor[0]

tensor([[ 1,  2,  3],
        [ 2,  3,  4],
        [12,  2,  4]])

### Random tensors


In [20]:
tensor = torch.rand(3, 4)
tensor

tensor([[0.8401, 0.6210, 0.2463, 0.1819],
        [0.3509, 0.0184, 0.5510, 0.9951],
        [0.1671, 0.5452, 0.6459, 0.1350]])

In [21]:
tensor.shape

torch.Size([3, 4])

In [22]:
tensor.ndim

2

In [23]:
image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channel
image_tensor

tensor([[[0.1587, 0.0085, 0.8974],
         [0.3837, 0.5479, 0.0351],
         [0.1054, 0.8244, 0.9880],
         ...,
         [0.9453, 0.9198, 0.8427],
         [0.5787, 0.9038, 0.2504],
         [0.4538, 0.4573, 0.9393]],

        [[0.5843, 0.7364, 0.0444],
         [0.6955, 0.0659, 0.8686],
         [0.4532, 0.6585, 0.2338],
         ...,
         [0.4349, 0.2975, 0.1039],
         [0.3473, 0.0260, 0.9417],
         [0.8673, 0.3460, 0.1447]],

        [[0.8753, 0.8774, 0.6879],
         [0.4346, 0.8738, 0.7137],
         [0.6674, 0.5719, 0.6276],
         ...,
         [0.0369, 0.7250, 0.8088],
         [0.8905, 0.5221, 0.3894],
         [0.2283, 0.7312, 0.5116]],

        ...,

        [[0.7463, 0.6639, 0.8357],
         [0.7504, 0.3834, 0.8693],
         [0.7906, 0.5945, 0.9616],
         ...,
         [0.6937, 0.1274, 0.8788],
         [0.9796, 0.7686, 0.3251],
         [0.8306, 0.7714, 0.4365]],

        [[0.4878, 0.8070, 0.9451],
         [0.1040, 0.7373, 0.1210],
         [0.

In [24]:
image_tensor.ndim

3

In [25]:
image_tensor.shape

torch.Size([224, 224, 3])